# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

permalink: 'log/:year/:month/:title'
relative_permalinks: false

# Setup
title:               "jmn: log - norlund (at) gmail"
tagline:             ''
description:         ''
url:                 'http://www.jmnorlund.net'
baseurl:             ''
paginate:            5
#theme:               jekyll-theme-minimal

# About/contact
author: jmn
# 
# Custom vars
version:             1.0.0
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme


remote_theme: Sylhare/Type-on-Strap
# mmistakes/hpstr-jekyll-theme
# swanson/lagom
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: csharp
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      
theme_settings:
  # Meta
  title: jmnorlund.net # blog's title
  avatar: assets/img/triangle.svg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  disqus_shortname: jmn-1
  # Header and footer text
#  header_text: > #two or three lines to describe your site
#     <p>Hi.</p>
#  header_text_feature_image: assets/img/pexels/triangular.jpeg
#  footer_text: >
#   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>
  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
