# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
permalink: 'log/:year/:month/:title'
relative_permalinks: false

# Setup
title:               "jmn: log - norlund (at) gmail"
tagline:             ''
description:         ''
url:                 'http://www.jmnorlund.net'
baseurl:             ''
paginate:            5
#theme:               jekyll-theme-minimal

# About/contact
author:
  name:              jmn
  url:               https://jmn.github.io
  email:             ''

# Custom vars
version:             1.0.0
