# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

permalink: 'log/:year/:month/:title'
relative_permalinks: false

# Setup
title:               "jmn: log - norlund (at) gmail"
tagline:             ''
description:         ''
url:                 'http://www.jmnorlund.net'
baseurl:             ''
paginate:            5
#theme:               jekyll-theme-minimal

# About/contact
author: jmn
# 
# Custom vars
version:             1.0.0
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme


remote_theme: Sylhare/Type-on-Strap
# mmistakes/hpstr-jekyll-theme
# swanson/lagom

highlighter: rouge
theme_settings:
  # Meta
  title: jmn's log
  avatar: 
  favicon: assets/favicon.ico
  gravatar: df5a6f68e6de417f563d5deaf26ea4e8 # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <p>Hello.</p>
#  header_text_feature_image: assets/img/pexels/triangular.jpeg
#  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>
